language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
cache:
  directories:
    - node_modules
before_install:
  - if [[ $(npm --version) == 2* ]]; then npm install -g npm@latest-3; fi
after_success:
  - npm i -g coveralls
  - cat coverage/remapped/lcov.info | coveralls
